apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: college-admission-dep
spec:
  selector:
    matchLabels:
      app: college-admission
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: college-admission
    spec:
      containers:
        - name: college-admission
          image: kovvurudhanush/college-admission:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster